# GitHub Sponsors funding options for LaunchPad

github: mikeartee
ko_fi: # your-kofi-username
buy_me_a_coffee: # your-buymeacoffee-username
patreon: # your-patreon-username
custom: # ["https://your-website.com/donate"]